TOPICS = [
    "Biology - cell structure and function",
    "Biology - genetics and evolution",
    "Biology - human body systems",
    "Biology - ecology and environment",
    "Biology - plants and photosynthesis",
    "Biology - microbiology and bacteria",
    "Biology - viruses and infectious diseases",
    "Biology - molecular biology techniques",
    "Biology - neuroscience and the brain",
    "Biology - biochemistry and metabolism",
    "Biology - biotechnology and genetic engineering",
    "Biology - immunology and the immune system",
    "Biology - developmental biology and life cycles",
    "Biology - marine biology and ocean ecosystems",
    "Biology - conservation biology and biodiversity",
    "Biology - animal behavior and ethology",
    "Biology - anatomy and physiology",
    "Biology - endocrinology and hormones",
    "Biology - pathology and disease mechanisms",
    "Biology - pharmacology and drug action",
]
